#!/bin/sh
# Copyright 2011 Marc-Antoine Ruel. All Rights Reserved. Use of this
# source code is governed by a BSD-style license that can be found in the
# LICENSE file.
sudo kill -9 `cat /tmp/.X0-lock`
# Not necessary, gdm or whoever restarts x automatically.
# startx
# run with nohup killx.sh
