#!/bin/bash
# Copyright 2025 Marc-Antoine Ruel. All Rights Reserved. Use of this
# source code is governed by a BSD-style license that can be found in the
# LICENSE file.
#
# Pull from a mydevenv container.

set -eu
cd "$(git rev-parse --show-toplevel)"

CONTAINER_NAME="cli-$(basename "$PWD")"
if [ $# -gt 1 ]; then
    echo "Usage: $0 [container_name]" >&2
    exit 1
elif [ $# -eq 1 ]; then
    CONTAINER_NAME="$1"
fi
BRANCH="$(git rev-parse --abbrev-ref HEAD)"
echo "Pushing $BRANCH to $CONTAINER_NAME..."
git push -f $CONTAINER_NAME
ssh $CONTAINER_NAME "cd /app && git reset --hard && git checkout $BRANCH"
