#!/bin/bash
# Copyright 2025 Marc-Antoine Ruel. All Rights Reserved. Use of this
# source code is governed by a BSD-style license that can be found in the
# LICENSE file.
#
# Pull from a mydevenv container.

set -eu

CONTAINER_NAME="cli-$(basename "$PWD")"
echo "Working on $CONTAINER_NAME..."
git push -f $CONTAINER_NAME
ssh $CONTAINER_NAME "cd /app && git reset --hard"
