#!/bin/bash
# Copyright 2025 Marc-Antoine Ruel. All Rights Reserved. Use of this
# source code is governed by a BSD-style license that can be found in the
# LICENSE file.
#
# Pull from a mydevenv container.

set -eu

CONTAINER_NAME="cli-$(basename "$PWD")"
BRANCH="$(git rev-parse --abbrev-ref HEAD)"
echo "Pushing $BRANCH to $CONTAINER_NAME..."
git push -f $CONTAINER_NAME
ssh $CONTAINER_NAME "cd /app && git reset --hard && git checkout $BRANCH"
