#!/bin/bash
# Copyright 2023 Marc-Antoine Ruel. All Rights Reserved. Use of this
# source code is governed by a BSD-style license that can be found in the
# LICENSE file.

# Rescale a video to a 15fps half-size GIF.
# Usage:
#  to_gif in.mp4
#
#  for i in *.mp4; do to_gif $i; done

set -eu

IN="$1"
shift
OUT="${IN%.*}.gif"

if [ -z "${FPS-}" ];then
  FPS=15
fi
if [ -z "${SCALE-}" ];then
  SCALE="scale=iw/2:ih/2"
  # SCALE="scale=2*iw/3:2*ih/3"
fi

echo "Generating palette"
ffmpeg -hide_banner -loglevel error -y -i "$IN" \
    -r $FPS \
    -vf "$SCALE" \
    -vf palettegen \
    palette.png

echo "Generating GIF fps=${FPS}, scale=${SCALE}"
ffmpeg -hide_banner -loglevel error -i "$IN" \
    -i palette.png \
    -r $FPS \
    -lavfi "paletteuse,$SCALE" \
    "$@" "$OUT"

rm palette.png
