#!/bin/bash
# Copyright 2023 Marc-Antoine Ruel. All Rights Reserved. Use of this
# source code is governed by a BSD-style license that can be found in the
# LICENSE file.

# Rescale a video to a 15fps half-size GIF.
# Usage:
#  to_gif in.mp4
#
#  for i in *.mp4; do to_gif $i; done

set -eu

IN="$1"
shift
OUT="${IN%.*}.gif"

if [ -z "${FPS-}" ];then
  FPS=15
fi
if [ -z "${SCALE-}" ];then
  SCALE="scale=iw/2:ih/2"
  # 2/3rd: SCALE="scale=2*iw/3:2*ih/3"
  # Original: SCALE="scale=iw:-1"
fi

# Reduce the palette to 32 colors:
#   palettegen=max_colors=32:reserve_transparent=0
# Do not use dithering for higher compression:
#   paletteuse=dither=none
VF="fps=$FPS,$SCALE:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse"

echo "Generating $OUT"
ffmpeg -hide_banner -loglevel error -i "$IN" -vf "$VF" "$@" "$OUT"
