# Copyright 2025 Marc-Antoine Ruel. All Rights Reserved. Use of this
# source code is governed by a BSD-style license that can be found in the
# LICENSE file.
#
# Dockerfile to create mydevenv.base

# We don't need it to be stuck on old images so just fetch whatever is current latest.
FROM debian:latest

# Install dependencies
RUN export DEBIAN_FRONTEND=noninteractive && \
	apt-get update -q && \
    apt-get install -q -y --no-install-recommends \
		build-essential \
		ca-certificates \
		curl \
		ffmpeg \
		git \
		gpg \
		less \
		openssh-server \
		python3 \
		python3-venv \
		rsync \
		shared-mime-info \
		wget \
		xvfb && \
	apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install Firefox from Mozilla's official APT repository
RUN curl -sSL -o /etc/apt/keyrings/packages.mozilla.org.asc https://packages.mozilla.org/apt/repo-signing-key.gpg && \
	echo 'deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main' > /etc/apt/sources.list.d/mozilla.list && \
	echo 'Package: *\nPin: origin packages.mozilla.org\nPin-Priority: 1000' > /etc/apt/preferences.d/mozilla && \
	apt-get update -q && \
	apt-get install -y --no-install-recommends firefox && \
	apt-get clean

# Install Geckodriver
RUN GECKODRIVER_VERSION=$(curl -sSL "https://api.github.com/repos/mozilla/geckodriver/releases/latest" | grep "tag_name" | cut -d : -f 2 | tr -d '", ' | cut -c2-) && \
	curl -sSL "https://github.com/mozilla/geckodriver/releases/download/v${GECKODRIVER_VERSION}/geckodriver-v${GECKODRIVER_VERSION}-linux64.tar.gz" | tar xz -C /usr/local/bin && \
	chmod +x /usr/local/bin/geckodriver

# Configure SSH
RUN echo 'PasswordAuthentication no' >> /etc/ssh/sshd_config.d/mydevenv.conf && \
    echo 'PubkeyAuthentication yes' >> /etc/ssh/sshd_config.d/mydevenv.conf && \
    echo 'HostbasedAuthentication yes' >> /etc/ssh/sshd_config.d/mydevenv.conf && \
    echo 'TrustedUserCAKeys /etc/ssh/container_ca.pub' >> /etc/ssh/sshd_config.d/mydevenv.conf
RUN rm -f /etc/ssh/ssh_host_*_key /etc/ssh/ssh_host_*_key.pub
COPY sketch/container_server_identity /etc/ssh/ssh_host_rsa_key
COPY sketch/container_server_identity.pub /etc/ssh/ssh_host_rsa_key.pub
COPY sketch/container_ca.pub /etc/ssh/
RUN echo 'Welcome to mydevenv!' > /etc/motd
COPY start.sh /root/start.sh

# Configure Bash (for everyone)
RUN curl -sSL -o /opt/git-completion.bash https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash && \
    echo 'export SHELL' >> /etc/profile.d/mydevenv.sh && \
    echo 'source /opt/git-completion.bash' >> /etc/profile.d/mydevenv.sh && \
    echo 'source /etc/bash_completion.d/git-prompt' >> /etc/profile.d/mydevenv.sh && \
    echo 'GIT_PS1_DESCRIBE_STYLE=tag' >> /etc/profile.d/mydevenv.sh && \
    echo 'GIT_PS1_SHOWCOLORHINTS=1' >> /etc/profile.d/mydevenv.sh && \
    echo 'GIT_PS1_SHOWDIRTYSTATE=1' >> /etc/profile.d/mydevenv.sh && \
    echo 'GIT_PS1_SHOWSTASHSTATE=1' >> /etc/profile.d/mydevenv.sh && \
    echo 'GIT_PS1_SHOWUNTRACKEDFILES=1' >> /etc/profile.d/mydevenv.sh && \
    echo 'GIT_PS1_SHOWUPSTREAM=auto' >> /etc/profile.d/mydevenv.sh && \
    echo 'function __my_ps1 {' >> /etc/profile.d/mydevenv.sh && \
    echo '  __git_ps1 \\' >> /etc/profile.d/mydevenv.sh && \
    echo '    "\\[\\e]0;\\W\\a\\]\\[\\e[0m\\]\\$(_V=\\$\\\?; if [ \\$_V != 0 ]; then echo -e -n \"\\\\[\\\\e[36m\\\\]$_V\\\\[\\\\e[0m\\\\]\" ; fi)" \\' >> /etc/profile.d/mydevenv.sh && \
    echo '    "\\[\\e[36m\\]\\w\\[\\e[0m\\]🐳 "' >> /etc/profile.d/mydevenv.sh && \
    echo '}' >> /etc/profile.d/mydevenv.sh && \
    echo 'PROMPT_COMMAND=__my_ps1' >> /etc/profile.d/mydevenv.sh && \
    echo 'export LS_OPTIONS="--color=auto"' >> /etc/profile.d/mydevenv.sh && \
    echo 'eval "$(dircolors)"' >> /etc/profile.d/mydevenv.sh && \
    echo "alias ls='ls \$LS_OPTIONS'" >> /etc/profile.d/mydevenv.sh && \
    echo "alias ll='ls \$LS_OPTIONS -la'" >> /etc/profile.d/mydevenv.sh

# Create user "user"
RUN adduser --disabled-password user
#RUN useradd -ms /bin/bash user && mkdir -p /app && chown user:user /app
RUN su user -c "mkdir -p /home/user/.ssh /home/user/.config/git"
COPY sketch/container_user_identity.pub /home/user/.ssh/authorized_keys
COPY config/git/config /home/user/.config/git/config
COPY config/git/ignore /home/user/.config/git/ignore
RUN echo "cd /app" >> /etc/profile.d/mydevenv.sh
RUN chown -R user:user /home/user/.ssh /home/user/.config
RUN chmod 0700 /home/user/.ssh
RUN chmod 0400 /home/user/.ssh/authorized_keys

# Create app directory (as user)
RUN mkdir /app
RUN chown user:user /app
RUN su user -c "git init /app"

# Start SSH server
CMD ["/root/start.sh"]
