#!/bin/sh
#Copyright 2016 (c) Marc-Antoine Ruel. All rights reserved.
# If you are seeing this file, I screwed up.
set -eu

# Install useful packages I can't live without.

sudo apt-get install -y \
  ifstat ntpdate openssh sysstat tmux vim
